# Yolo
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master      
jobs:
  soSomething:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - run: ls
    #- run: azcopy copy .\* '${{secrets.STORAGE_ACCOUNT_SAS_TOKEN}}'
    - name: Deploy to Azure Storage
      uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
      with:        
        source-path: .     
        sas-url: "${{secrets.STORAGE_ACCOUNT_SAS_TOKEN}}"
        
